test_that("tickers identical in company and quality",{
  data(companies)
  data(financials)
  data(prices)
  data(quality)
  temp_profitability <- qmj::market_profitability(companies,financials)
  temp_growth <- qmj::market_growth(companies,financials)
  temp_safety <- qmj::market_safety(companies,financials,prices)
  temp_payouts <- qmj::market_payouts(companies,financials)
  expect_that(length(intersect(companies$ticker,quality$ticker)),equals(length(companies$ticker)))
  expect_that(length(intersect(companies$ticker,temp_profitability$ticker)),equals(length(companies$ticker)))
  expect_that(length(intersect(companies$ticker,temp_growth$ticker)),equals(length(companies$ticker)))
  expect_that(length(intersect(companies$ticker,temp_safety$ticker)),equals(length(companies$ticker)))
  expect_that(length(intersect(companies$ticker,temp_payouts$ticker)),equals(length(companies$ticker)))
}) 