test_that("companies list has ticker column", {
  x <- data.frame(name = "test")
  data(financials)
  data(prices)
  expect_error(qmj::get_info(x),"parameter requires a ticker column.")
  expect_error(qmj::get_prices(x),"parameter requires a ticker column.")
  expect_error(qmj::market_data(x,financials,prices),"first parameter requires a ticker column.")
  expect_error(qmj::market_profitability(x,financials),"first parameter requires a ticker column.")
  expect_error(qmj::market_growth(x,financials),"first parameter requires a ticker column.")
  expect_error(qmj::market_safety(x,financials,prices),"first parameter requires a ticker column.")
  expect_error(qmj::market_payouts(x,financials),"first parameter requires a ticker column.")
})