#' Gets company balance sheets, income statements, and cash flows.
#'
#' Retrieves data for the data frame of companies generated by 
#' getcompanies() and writes associated cashflow statements, 
#' income statements, and balance sheets into a data frame.
#' @param companies A data frame of companies. Must have a ticker column.
#' @examples
#' \dontrun{
#' data(companies)
#' get_info(companies)
#' }
#' @export

get_info <- function(x) {
  filepath <- system.file("data", package="qmj")
  tickers <- as.character(x$ticker)
  cashflows <- list()
  incomestatements <- list()
  balancesheets <- list()
  n <- 1
  k <- 1
  c <- 1
  for(i in tickers) {
    prospective <- tryCatch(quantmod::getFinancials(i,auto.assign = FALSE),
                            error=function(e) {
                              e
                            })
    matr <- matrix()
    if(!inherits(prospective,"error")) {
      if(nrow(matr <- quantmod::viewFinancials(prospective,type = 'CF',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a <- a + 1
        }
        cashflows[[n]] <- matr
        n <- n+1
      }
      if(nrow(matr <- quantmod::viewFinancials(prospective,type = 'IS',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a <- a + 1
        }
        incomestatements[[k]] <- matr
        k <- k+1
      }
      if(nrow(matr <- quantmod::viewFinancials(prospective,type = 'BS',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a <- a + 1
        }
        balancesheets[[c]] <- matr
        c <- c+1
      }
    }
  }
  list(cashflows, incomestatements, balancesheets)
  
#   filepath <- system.file("extdata", package="qmj")
#   filepath2 <- paste(filepath, "/cashflows.RData", sep='')
#   save(cashflows, file=filepath2)
#   #save(cashflows,file="~/econ20/R Paper/qmj/extdata/instcashflows.RData")
#   
#   filepath2 <- paste(filepath, "/incomestatements.RData", sep='')
#   save(incomestatements, file=filepath2)
#   #save(incomestatements,file="~/econ20/R Paper/qmj/inst/extdata/incomestatements.RData")
#   
#   filepath2 <- paste(filepath, "/balancesheets.RData", sep='')
#   save(balancesheets, file=filepath2)
#   #save(balancesheets,file="~/econ20/R Paper/qmj/inst/extdata/balancesheets.RData")
}