#' getbalancesheets
#'
#' Retrieves data from the list of companies generated by getcompanies() and 
#' writes associated balance sheets into a data frame.
#' @examples
#' getbalancesheets()
#' @export

getbalancesheets <- function() {
  filepath <- system.file("data", package="qmj")
  companies <- read.csv(paste(filepath, "/companies.csv", sep=''))
  tickers <- as.character(companies$tickers)
  vect <- list()
  n <- 1
  for(i in tickers) {
    prospective <- tryCatch(getFinancials(i,auto.assign = FALSE),
                  error=function(e) {
                  e
                  })
    matr <- matrix()
    if(!inherits(prospective,"error") && nrow(matr <- viewFinancials(prospective,type = 'BS',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a = a + 1
        }
        vect[[n]] <- matr
        n = n+1
    } else {
      vect[[n]] <- matrix(dat=NA, ncol=4, nrow=42)
      n = n+1
    }
  }
  filepath <- paste(filepath, "/balancesheets.csv", sep='')
  write.csv(vect,file=filepath)
}