#' getinfo
#'
#' Retrieves data from the list of companies generated by 
#' getcompanies() and writes associated cashflow statements, 
#' income statements, and balance sheets into a data frame.
#' @examples
#' \donttest{
#' getinfo()
#' }
#' @export

getinfo <- function() {
  filepath <- system.file("data", package="qmj")
  filepath1 <- paste(filepath, "/companies.RData", sep='')
  load(filepath1)
  tickers <- as.character(companies$tickers)
  cashflows <- list()
  incomestatements <- list()
  balancesheets <- list()
  n <- 1
  k <- 1
  c <- 1
  for(i in tickers) {
    prospective <- tryCatch(quantmod::getFinancials(i,auto.assign = FALSE),
                            error=function(e) {
                              e
                            })
    matr <- matrix()
    if(!inherits(prospective,"error")) {
      if(nrow(matr <- quantmod::viewFinancials(prospective,type = 'CF',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a <- a + 1
        }
        cashflows[[n]] <- matr
        n <- n+1
      } else {
        cashflows[[n]] <- matrix(dat=NA, ncol=4, nrow=19)
        n <- n+1
      }
      if(nrow(matr <- quantmod::viewFinancials(prospective,type = 'IS',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a <- a + 1
        }
        incomestatements[[k]] <- matr
        k <- k+1
      } else {
        incomestatements[[k]] <- matrix(dat=NA, ncol=4, nrow=49)
        k <- k+1
      }
      if(nrow(matr <- quantmod::viewFinancials(prospective,type = 'BS',period = 'A'))) {
        a <- 1
        while(a <= length(colnames(matr))) {
          colnames(matr)[a] <- sub("[-][0-9]*[-][0-9]*","",paste(i,colnames(matr)[a]))
          a <- a + 1
        }
        balancesheets[[c]] <- matr
        c <- c+1
      } else {
        balancesheets[[c]] <- matrix(dat=NA, ncol=4, nrow=42)
        c <- c+1
      }
    }
  }
  filepath2 <- paste(filepath, "/cashflows.RData", sep='')
  save(cashflows, file=filepath2)
  
  filepath2 <- paste(filepath, "/incomestatements.RData", sep='')
  save(incomestatements, file=filepath2)
  
  filepath2 <- paste(filepath, "/balancesheets.RData", sep='')
  save(balancesheets, file=filepath2)
}