#' Makes raw financial data usable and readable.
#'
#' \code{tidyinfo} works by formatting and curtailing the raw data generated by quantmod (and, by extension, the \code{get_info} function of this package)
#' @param x A list of lists of financial statements. Generated from get_info(companies).
#' @return Returns a data set that is usable by the other functions of this package, as well as being generally more readable.
#' @seealso \code{\link{get_info}}
#' @seealso \code{\link{tidy_prices}}
#' @seealso \code{\link{tidy_cashflows}}
#' @seealso \code{\link{tidy_balancesheets}}
#' @seealso \code{\link{tidy_incomestatements}}
#' @examples
#' \dontrun{
#' data(companies)
#' raw_data <- get_info(companies)
#' financials <- tidyinfo(raw_data)
#' 
#' my_companies <- data.frame(ticker=c("GOOG", "IBM", "FLWS"))
#' raw_data <- get_info(my_companies)
#' financials <- tidyinfo(my_companies)
#' }
#' @export

tidyinfo <- function(x){
  #Index is the current structure of the output of the get_info function.
  tidycash <- tidy_cashflows(x[[1]])
  tidyincome <- tidy_incomestatements(x[[2]])
  tidybalance <- tidy_balancesheets(x[[3]])

  financials <- merge(tidybalance, merge(tidycash, tidyincome, by=c("ticker", "year")), by=c("ticker", "year"))
  financials <- unique(financials)
  
  #The columns below are the only ones used in our formulas, and so the other columns are culled out.
  keep <- c("ticker","year","AM","CWC","CX","DIVC",
            "DO","DP.DPL","GPROF","IAT","IBT","NI",
              "NINT","NRPS","RPS","TA","TCA","TCL",
                     "TCSO","TD","TL","TLSE","TREV")
  financials$AM <- as.numeric(financials$AM)
  financials$CWC <- as.numeric(financials$CWC)
  financials$CX <- as.numeric(financials$CX)
  financials$DIVC <- as.numeric(financials$DIVC)
  financials$DO <- as.numeric(financials$DO)
  financials$DP.DPL <- as.numeric(financials$DP.DPL)
  financials$GPROF <- as.numeric(financials$GPROF)
  financials$IAT <- as.numeric(financials$IAT)
  financials$IBT <- as.numeric(financials$IBT)
  financials$NI <- as.numeric(financials$NI)
  financials$NINT <- as.numeric(financials$NINT)
  financials$NRPS <- as.numeric(financials$NRPS)
  financials$RPS <- as.numeric(financials$RPS)
  financials$TA <- as.numeric(financials$TA)
  financials$TCA <- as.numeric(financials$TCA)
  financials$TCL <- as.numeric(financials$TCL)
  financials$TCSO <- as.numeric(financials$TCSO)
  financials$TD <- as.numeric(financials$TD)
  financials$TL <- as.numeric(financials$TL)
  financials$TLSE <- as.numeric(financials$TLSE)
  financials$TREV <- as.numeric(financials$TREV)
  financials[keep]
}